### ISSUE TITLE
Upgrade existing installation to latest version

### ISSUE THREAD

**Issue by look4regev** [andrewrothstein/ansible-terraform#16]
As far as I see, running this playbook on a server with already existing installation, the playbook will skip rather than upgrade to latest version (https://github.com/andrewrothstein/ansible-terraform/blob/master/tasks/main.yml#L8).
Will it be possible please to make the changes to support also upgrading? Or is there something I am missing?
Thank you.

**Comment by andrewrothstein** [comment]
It will both upgrade and downgrade leaving the existing installs in place. terraform_binary_dir has terrafrom_name in it which has the version in it. It will never redownload/reinstall a version that's already there.
