### ISSUE TITLE
May be a different version to Ansible Galaxy

### ISSUE THREAD

**Issue by goffinf** [andrewrothstein/ansible-terraform#25]
Thanks for maintaining a number of really useful Ansible roles.

Ansible Galaxy version v2.2.70 links to this github repo. However when running the role Terraform version installed is **1.0.1** rather than the **1.0.2** declared as the default ?

https://github.com/andrewrothstein/ansible-terraform/blob/master/defaults/main.yml

```
---
terraform_ver: 1.0.2
...
```
The following error occurs:

```
TASK [andrewrothstein.terraform : downloading https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip...] ********************************************************************************
fatal: [wsl2.local]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '1.0.2'

    The error appears to be in '/c/Data/wsl2/ansible/roles/andrewrothstein.terraform/tasks/main.yml': line 10, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

      block:
        - name: downloading {{ terraform_url }}...
          ^ here
    ...
```

Any chance of creating a 1.0.4 version.

Kind Regards

Fraser

**Comment by andrewrothstein** [comment]
You're welcome Fraser!
I just added the checksums for v1.0.3 and v1.0.4 and published v2.2.72 of this role to the galaxy. Enjoy!
Drew
